global HEADERS
from .abbreviation import state_abbreviation,country_code,gender_code
from .options import method_configuration,recursive_data_render,success_output,check_obligation
from .constant import REQUESTS_OBLIGATED,HEADERS